int A = new Random().Next(1, 1000);
int B = new Random().Next(1, 1000);
int C = new Random().Next(1, 1000);
Console.WriteLine(A);
Console.WriteLine(B);
Console.WriteLine(C);
int max = A;
if(A > max) max = A;
if(B > max) max = B;
if(C > max) max = C;
Console.Write("Максимальное число: ");
Console.WriteLine(max);
